---
- name: Ensure user is present
  become: yes
  user:
    name: "{{ user }}"
    state: present
    groups: "docker"
    uid: 1001

- name: Ensure you'll be able to deploy later on
  become: true
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', public_key }}"
    state: present
    manage_dir: yes

